version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    command: nodemon server.js
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
