name: Publish Docker image

on:
  push:
    branches: [master]

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Hub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Container Hub (result)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/subicura/voting/result:latest
          file: ./result/Dockerfile
          context: ./result
          labels: |
            org.opencontainers.image.source=https://github.com/subicura/example-voting-app
      - name: Push to GitHub Container Hub (vote)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/subicura/voting/vote:latest
          file: ./vote/Dockerfile
          context: ./vote
          labels: |
            org.opencontainers.image.source=https://github.com/subicura/example-voting-app
      - name: Push to GitHub Container Hub (worker)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/subicura/voting/worker:latest
          file: ./worker/Dockerfile
          context: ./worker
          labels: |
            org.opencontainers.image.source=https://github.com/subicura/example-voting-app
